baseurl: "/"
title: r8teful
theme: ghostwriter
languageCode: en-us
copyright: My name

services:
  googleAnalytics:
    ID: G-JBFLLZQGZ1

privacy:
  disqus:
    disable: true
  googleAnalytics:
    anonymizeIP: true
    respectDoNotTrack: true
    useSessionStorage: false

taxonomies:
  tag: tags

params:
  mainSections:
  intro: true
  headline: r8teful
  description: I make games!
  github: "https://github.com/r8teful"
  twitter: "https://twitter.com/r8teful"
  email: r8tefulgames@gmail.com
  opengraph: true
  shareTwitter: true
  rss: true
  shareFacebook: true
  shareLinkedIn: false
  dateFormat: "Mon, Jan 2, 2006"
  exponeaJsUrl: ""
  exponeaTarget: ""
  exponeaToken: ""
  exponeaTrackVisits: false
  readingTime: true
  readingTimeText: "Estimated reading time:"
  fathomUrl: ""
  fathomSiteId: ""

menu:
  main:
    - name: Blog
      url: /post/
      weight: 2
    - name: Games
      url: /Games/
      weight: 1
    - name: About
      url: /about
      weight: 3
