baseurl = "/"
title = "r8teful"
theme = "ghostwriter"

[Params]
    mainSections = ["post"]
    intro = true
    headline = "r8teful"
    description = "I make games and stuff"
    github = "https://github.com/r8teful"
    twitter = "https://twitter.com/r8teful"
    email = "r8tefulgames@gmail.com"
    opengraph = true
    shareTwitter = true
    dateFormat = "Mon, Jan 2, 2006"

[Permalinks]
    post = "/:filename/"